# Generated by Django 4.0.6 on 2022-07-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deposit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
