# Generated by Django 4.0.6 on 2022-07-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='approved_date',
            new_name='hire_date',
        ),
    ]
